const chapters=[
  {start:0,end:10,label:'开场 · 10 秒',title:'欢迎来到小手机工坊',keys:['AI 陪伴小手机','无需代码','自由搭建'],text:'欢迎来到 LovePhone Studio，小手机工坊。它可以帮助你用简单的选择和配置，制作一台属于自己的 AI 陪伴小手机。'},
  {start:10,end:28,label:'功能 · 18 秒',title:'像搭积木一样选择 App',keys:['角色','聊天','音乐','记忆'],text:'首先，你可以像搭积木一样选择需要的功能。聊天、角色和设置是基础能力，音乐、记忆、日记和纪念日等功能可以自由添加。'},
  {start:28,end:48,label:'角色与聊天 · 20 秒',title:'创建专属的陪伴角色',keys:['角色设定','自己的 AI','独立模型'],text:'接着，创建自己的陪伴角色。填写名字、称呼、性格和说话方式，再连接你自己的 AI 服务，就可以开始聊天。不同角色也可以使用各自独立的设定和模型。'},
  {start:48,end:68,label:'音乐 · 20 秒',title:'不只有聊天',keys:['搜索歌曲','桌面唱片机','播放联动'],text:'LovePhone 不只有聊天。音乐 App 可以搜索和播放歌曲，播放状态还会同步到桌面的唱片组件，让小手机更像一台真正属于你的设备。'},
  {start:68,end:88,label:'美化 · 20 秒',title:'所见即所得地自由美化',keys:['手机壳','颜色','图标','小组件'],text:'在美化页面中，可以更换手机壳、颜色、图标和桌面组件。所有修改都会实时显示在右侧，不需要写代码，也能慢慢搭出自己喜欢的样子。'},
  {start:88,end:103,label:'保存 · 15 秒',title:'保存、备份或下载',keys:['浏览器本地','JSON 备份','独立 HTML'],text:'制作完成后，可以保存在当前浏览器、导出 JSON 备份，也可以下载成本地 HTML。'},
  {start:103,end:115,label:'完成 · 12 秒',title:'把它变成只属于你的小手机',keys:['选择功能','创建角色','完成'],text:'这就是 LovePhone Studio。选择功能，创建角色，再把它变成只属于你的小手机。'}
];
const total=115;let elapsed=0,playing=false,lastFrame=0,active=-1;
const $=id=>document.getElementById(id),stage=$('stage'),overlay=$('startOverlay'),playBtn=$('playBtn');
function fit(){const scale=Math.min(innerWidth/1920,innerHeight/1080);stage.style.transform=`scale(${scale})`}
function format(s){s=Math.max(0,Math.min(total,Math.floor(s)));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function setChapter(index,restartMedia=true){index=Math.max(0,Math.min(chapters.length-1,index));const c=chapters[index];active=index;$('chapterCount').textContent=`${String(index+1).padStart(2,'0')} / 07`;$('eyebrow').textContent=c.label;$('scriptTitle').textContent=c.title;$('scriptText').textContent=c.text;$('keywords').innerHTML=c.keys.map(k=>`<span>${k}</span>`).join('');document.querySelectorAll('.scene').forEach((s,i)=>s.classList.toggle('active',i===index));document.querySelectorAll('.chapter-buttons button,.timeline-marks button').forEach((b,i)=>b.classList.toggle('active',i===index));document.querySelectorAll('video').forEach(v=>{v.pause();if(restartMedia)v.currentTime=0});const video=document.querySelector(`.scene[data-scene="${index}"] video`);if(video&&playing){video.currentTime=0;video.play().catch(()=>{})}}
function seek(value){elapsed=Math.max(0,Math.min(total,value));const index=chapters.findIndex(c=>elapsed>=c.start&&elapsed<c.end);setChapter(index<0?chapters.length-1:index);render()}
function render(){const index=chapters.findIndex(c=>elapsed>=c.start&&elapsed<c.end);if(index>=0&&index!==active)setChapter(index);$('timelineFill').style.width=`${elapsed/total*100}%`;$('timecode').textContent=`${format(elapsed)} / 01:55`;playBtn.textContent=playing?'Ⅱ':'▶';playBtn.classList.toggle('active',playing)}
function tick(now){if(playing){if(!lastFrame)lastFrame=now;elapsed+=(now-lastFrame)/1000;if(elapsed>=total){elapsed=total;playing=false}render()}lastFrame=now;requestAnimationFrame(tick)}
function play(){playing=!playing;lastFrame=performance.now();const v=document.querySelector('.scene.active video');if(v)(playing?v.play():v.pause()).catch(()=>{});render()}
function start(clean=false){document.body.classList.toggle('clean',clean);overlay.classList.add('hidden');elapsed=0;playing=true;setChapter(0);lastFrame=performance.now();render()}
chapters.forEach((c,i)=>{const mark=document.createElement('button');mark.style.left=`${c.start/total*100}%`;mark.title=c.title;mark.onclick=()=>seek(c.start);$('timelineMarks').append(mark);const btn=document.createElement('button');btn.textContent=i+1;btn.title=c.title;btn.setAttribute('aria-label',`跳到第 ${i+1} 章：${c.title}`);btn.onclick=()=>seek(c.start);$('chapterButtons').append(btn)});
$('startBtn').onclick=()=>start(false);$('cleanStartBtn').onclick=()=>start(true);playBtn.onclick=play;$('restartBtn').onclick=()=>{overlay.classList.remove('hidden');playing=false;seek(0)};$('cleanBtn').onclick=()=>document.body.classList.toggle('clean');$('timeline').onclick=e=>seek((e.offsetX/e.currentTarget.clientWidth)*total);
document.querySelectorAll('[data-live]').forEach(b=>b.onclick=()=>{const t=$('toast');t.textContent=`已打开${b.dataset.live} App`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)});
addEventListener('resize',fit);addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();play()}if(e.key.toLowerCase()==='h')document.body.classList.toggle('clean');if(e.key.toLowerCase()==='r'){$('restartBtn').click()}if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.();if(e.key==='ArrowRight')seek(chapters[Math.min(active+1,6)].start);if(e.key==='ArrowLeft')seek(chapters[Math.max(active-1,0)].start)});fit();setChapter(0);render();requestAnimationFrame(tick);
